// Coordenadas (x, y) en % sobre la imagen del mapa.
// La posición se basa en la comuna del colegio, con un pequeño offset
// cuando hay varios colegios en la misma comuna.
//
// Para reposicionar un icono manualmente, edita los campos `x` e `y` (porcentaje).

const SCHOOLS = [
  {
    nombre: "Colegio San Francisco de Asís de Angol",
    rbd: "5264",
    dependencia: "Particular Subvencionado",
    provincia: "Malleco",
    comuna: "Angol",
    direccion: "Purén 747, Angol",
    x: 33.0, y: 16.0,
  },
  {
    nombre: "Escuela Diego Dublé Urrútía",
    rbd: "5226",
    dependencia: "Municipalidad DAEM",
    provincia: "Malleco",
    comuna: "Angol",
    direccion: "Los Copihues 520, Angol",
    x: 35.5, y: 18.0,
  },
  {
    nombre: "Escuela Particular Rucatraro N°377",
    rbd: "6583",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Carahue",
    direccion: "Sector Rucatraro S/N, Carahue",
    x: 30.0, y: 55.0,
  },
  {
    nombre: "Escuela Pública Tranapuente",
    rbd: "6504",
    dependencia: "Servicio Local de Educación Pública (SLEP)",
    provincia: "Cautín",
    comuna: "Carahue",
    direccion: "Camino Carahue-Nehuentue Km.19, Carahue",
    x: 28.0, y: 53.5,
  },
  {
    nombre: "Liceo Agrícola Cholchol",
    rbd: "6641",
    dependencia: "Particular Subvencionado",
    provincia: "Cautín",
    comuna: "Cholchol",
    direccion: "Teodoro Schmidt 389, Cholchol",
    x: 33.0, y: 47.5,
  },
  {
    nombre: "Escuela Ramón Ramírez Henríquez",
    rbd: "5348",
    dependencia: "Municipalidad DAEM",
    provincia: "Malleco",
    comuna: "Curacautín",
    direccion: "Ruta internacional 181 Km.87, Curacautín",
    x: 64.0, y: 41.5,
  },
  {
    nombre: "Fund. Educ. Escuela Part. Santa Elena",
    rbd: "53724",
    dependencia: "Particular subvencionado",
    provincia: "Malleco",
    comuna: "Curacautín",
    direccion: "Miraflores 245, Curacautín",
    x: 61.5, y: 43.5,
  },
  {
    nombre: "Escuela Particular N°2 Catripulli",
    rbd: "6039",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Curarrehue",
    direccion: "Camino Internacional 801, Localidad Catripulli, Curarrehue",
    x: 63.0, y: 78.0,
  },
  {
    nombre: "Escuela Básica Trabunquillem",
    rbd: "6715",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Galvarino",
    direccion: "Camino Rucatrato km.14, Galvarino",
    x: 36.0, y: 40.5,
  },
  {
    nombre: "Vallepenco",
    rbd: "5878",
    dependencia: "Particular Subvencionado",
    provincia: "Cautín",
    comuna: "Lautaro",
    direccion: "Camino Lautaro Galvarino KM 20, Lautaro",
    x: 45.5, y: 38.5,
  },
  {
    nombre: "Escuela Municipal Domitila Pinna Parra",
    rbd: "6305",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Loncoche",
    direccion: "Esmeralda s/n, Loncoche",
    x: 42.0, y: 87.0,
  },
  {
    nombre: "Colegio San Bernardo",
    rbd: "5725",
    dependencia: "Particular Subvencionado",
    provincia: "Cautín",
    comuna: "Padre Las Casas",
    direccion: "La Paz 161, Padre Las Casas",
    x: 41.5, y: 51.0,
  },
  {
    nombre: 'Escuela Municipal Rural F-485 "Truf-Truf"',
    rbd: "5625",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Padre Las Casas",
    direccion: "Camino Niagara Km.6, Padre Las Casas",
    x: 44.5, y: 52.5,
  },
  {
    nombre: "Escuela Particular N°65 La Estrella",
    rbd: "5894",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Perquenco",
    direccion: "Reducción Pichunlao, a 18 Km. al Noroeste de Lautaro, Perquenco",
    x: 49.0, y: 34.0,
  },
  {
    nombre: "Liceo Bicentenario Ciencias y Humanidades",
    rbd: "6223",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Pitrufquén",
    direccion: "León Gallo Sur 665, Pitrufquén",
    x: 38.5, y: 67.5,
  },
  {
    nombre: "Sala Cuna y Jardín Infantil Rukalaf",
    rbd: "34920",
    dependencia: "Sala Cuna/Jardín Infantil JUNJI",
    provincia: "Cautín",
    comuna: "Pitrufquén",
    direccion: "Caupolicán Calfuquir 580, Pitrufquén",
    x: 36.5, y: 69.0,
  },
  {
    nombre: "Complejo Educacional Pablo Sexto",
    rbd: "6070",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Pucón",
    direccion: "Uruguay 465, Pucón",
    x: 58.0, y: 78.0,
  },
  {
    nombre: "Escuela Paillaco",
    rbd: "6069",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Pucón",
    direccion: "Camino KM 30 Parque Nacional Huerquehue, Pucón",
    x: 60.0, y: 76.0,
  },
  {
    nombre: "Escuela Sol Naciente",
    rbd: "6471",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Saavedra",
    direccion: "Romopulli Km.20, Saavedra",
    x: 28.0, y: 58.5,
  },
  {
    nombre: "Colegio Emprender Temuco",
    rbd: "19983",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Temuco",
    direccion: "Milano 02025, Temuco",
    x: 41.0, y: 44.0,
  },
  {
    nombre: "Complejo Educacional Un Amanecer en La Araucanía",
    rbd: "5590",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Temuco",
    direccion: "Garibaldi 1225, Temuco",
    x: 44.0, y: 44.0,
  },
  {
    nombre: "Escuela Arturo Prat Temuco",
    rbd: "5575",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Temuco",
    direccion: "General Mackenna 685, Temuco",
    x: 42.5, y: 46.0,
  },
  {
    nombre: "Escuela Collimallin",
    rbd: "5647",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Temuco",
    direccion: "Collimallin s/n, Temuco",
    x: 40.0, y: 47.5,
  },
  {
    nombre: "Escuela Conoco Chico",
    rbd: "5633",
    dependencia: "Municipalidad DAEM",
    provincia: "Cautín",
    comuna: "Temuco",
    direccion: "Conoco - Chico s/n, Temuco",
    x: 45.0, y: 47.5,
  },
  {
    nombre: "Escuela Particular N°15 AMI",
    rbd: "19923",
    dependencia: "Particular Subvencionado",
    provincia: "Cautín",
    comuna: "Temuco",
    direccion: "Malvoa 920, Temuco",
    x: 41.5, y: 49.0,
  },
  {
    nombre: "Liceo Industrial de Temuco",
    rbd: "5566",
    dependencia: "Corporación Municipal",
    provincia: "Cautín",
    comuna: "Temuco",
    direccion: "Uruguay 1398, Temuco",
    x: 44.5, y: 49.0,
  },
  {
    nombre: "Escuela Pública Estación Toltén",
    rbd: "6358",
    dependencia: "Servicio Local de Educación Pública (SLEP)",
    provincia: "Cautín",
    comuna: "Teodoro Schmidt",
    direccion: "Sector Punta de Riel, Teodoro Schmidt",
    x: 28.0, y: 70.0,
  },
  {
    nombre: "Liceo Lucila Godoy Alcayaga",
    rbd: "5440",
    dependencia: "Municipalidad DAEM",
    provincia: "Malleco",
    comuna: "Traiguén",
    direccion: "Basilio Urrutia 970, Traiguén",
    x: 41.0, y: 27.5,
  },
  {
    nombre: "Liceo Bicentenario Padre Nicolás de Vilcún",
    rbd: "5921",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Vilcún",
    direccion: "Almirante Latorre 242, Vilcún",
    x: 53.5, y: 39.0,
  },
  {
    nombre: "Colegio de Humanidades de Villarrica",
    rbd: "6112",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Villarrica",
    direccion: "Gerónimo de Alderete 1027, Villarrica",
    x: 46.0, y: 81.5,
  },
  {
    nombre: "Liceo Bicentenario de Excelencia San Agustín de Licán Ray",
    rbd: "6115",
    dependencia: "Particular subvencionado",
    provincia: "Cautín",
    comuna: "Villarrica",
    direccion: "Cacique Millañaco esquina Gabriela Mistral, Villarrica",
    x: 49.0, y: 83.5,
  },
];
